# Любые ваши существующие настройки могут идти выше:

# Говорим Jekyll, какие папки НЕ обрабатывать:
exclude:
  - client-app
  - node_modules
# Если в будущем захотите игнорировать ещё папки или файлы,
# просто добавляйте их под этим списком:
#   - secret-data
#   - another-folder
